version: '3'
services:
  app:
    build:
      target: dev
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  app-prod:
    build:
      target: prod
      context: .
    ports:
      - '8080:80'
# ! COMMANDS
# docker-compose build <app or app-prod>
# docker-compose up <app or app-prod>

# For pushing to hub, change to your username/<image name> like =
# docker tag <image_name> <user_name>/<image_name>
# Specify the port while running
